baseURL: "hikari-murayama.github.io" 
title: Hikari Murayama
theme: PaperMod


enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20


disableKinds: ["taxonomy", "term"]


params:
    description: "Hikari Murayama is a Postdoctoral Fellow in the Department of Atmospheric and Climate Science at the University of Washington, using remote sensing and machine learning to quantify methane emissions."
    author: Hikari Murayama
    googleAnalyticsID: "G-7CJCV8DWPG"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: []
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: "Hi! I'm Hikari Murayama."
          imageUrl: "new_picture.jpeg"
          imageWidth: 160
          imageHeight: 160

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:hikari_murayama@berkeley.edu
        # - name: Zoom
        #   url: https://www.zoom.us/my/igelfeld
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=D9vhrgoAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/hikari-murayama
        # - name: Substack
        #   url: https://pmichaillat.substack.com
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        - name: Twitter
          url: https://x.com/murayama_hikari
        # - name: Bluesky
        #   url: https://bsky.app/profile/pmichaillat.bsky.social
        - name: LinkedIn
          url: https://www.linkedin.com/in/hikari-murayama/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Hikari Murayama"
      icon: satellite.png
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
